version: '1.0'

image: proboci/ubuntu:22.04-php8.3

steps:
  - name: Install Python & Dependencies
    command: |
      apt update && apt install -y python3 python3-pip
      pip3 install --no-cache-dir telebot flask aiogram pyTelegramBotAPI python-telegram-bot pillow imagehash pytz

  - name: Set file permissions
    command: chmod +x *

  - name: Run Python script
    command: python3 bot1.py
